package com.reoky.raidframer.core.definitions

/**
 * Additional spell IDs that indicate a real player is casting.
 * These are spells that don't belong to any of the 13 player skill trees,
 * aren't utility items, gliders, or potions, but are only castable by real players.
 *
 * Examples include Fold Wings, Summon Anywhere Warehouse, and other player-specific actions.
 */
data class PlayerBehaviorSpell(
  val spellId: Int,
  val spellName: String,
  val description: String
)

val PLAYER_BEHAVIOR_SPELLS: Map<Int, PlayerBehaviorSpell> = listOf(
  PlayerBehaviorSpell(34031, "Fold Wings", "Player action to fold glider wings"),
  PlayerBehaviorSpell(33820, "Summon Anywhere Warehouse", "Player action to summon warehouse access"),
  // Drinks
  PlayerBehaviorSpell(9001248, "Drink Ancient's Potion", "Consumable drink"),
  PlayerBehaviorSpell(9002792, "Drink Ancient's Potion", "Consumable drink"),
  PlayerBehaviorSpell(9002793, "Drink Ancient's Potion", "Consumable drink"),
  PlayerBehaviorSpell(39054, "Drink Banana Milk", "Consumable drink"),
  PlayerBehaviorSpell(47908, "Drink Blessing Potion", "Consumable drink"),
  PlayerBehaviorSpell(43338, "Drink Blue Tapioca", "Consumable drink"),
  PlayerBehaviorSpell(39067, "Drink Chocolate Milk", "Consumable drink"),
  PlayerBehaviorSpell(8000052, "Drink Elixir", "Consumable drink"),
  PlayerBehaviorSpell(8000054, "Drink Elixir", "Consumable drink"),
  PlayerBehaviorSpell(8000162, "Drink Energizing Spirits", "Consumable drink"),
  PlayerBehaviorSpell(9001849, "Drink Grape Soda", "Consumable drink"),
  PlayerBehaviorSpell(9001847, "Drink Lemon Soda", "Consumable drink"),
  PlayerBehaviorSpell(28661, "Drink Milk", "Consumable drink"),
  PlayerBehaviorSpell(39468, "Drink Moonlight Juice", "Consumable drink"),
  PlayerBehaviorSpell(9003425, "Drink Moonlight Juice", "Consumable drink"),
  PlayerBehaviorSpell(9001848, "Drink Orange Soda", "Consumable drink"),
  PlayerBehaviorSpell(8000160, "Drink Potent Stout", "Consumable drink"),
  PlayerBehaviorSpell(9002814, "Drink Potion", "Consumable drink"),
  PlayerBehaviorSpell(43337, "Drink Red Tapioca", "Consumable drink"),
  PlayerBehaviorSpell(8000161, "Drink Soothing Tonic", "Consumable drink"),
  PlayerBehaviorSpell(39502, "Drink Sunlight Juice", "Consumable drink"),
  PlayerBehaviorSpell(9003426, "Drink Sunlight Juice", "Consumable drink"),
  PlayerBehaviorSpell(27939, "Drink the Mountain Breeze", "Consumable drink"),
  PlayerBehaviorSpell(9002411, "Drink the poison", "Consumable drink"),
  // Food
  PlayerBehaviorSpell(9003085, "Eat Bite-Sized Cake in One Bite", "Consumable food"),
  PlayerBehaviorSpell(17074, "Eat Blue Flower Fruit", "Consumable food"),
  PlayerBehaviorSpell(30551, "Eat Candy", "Consumable food"),
  PlayerBehaviorSpell(8000039, "Eat Candy", "Consumable food"),
  PlayerBehaviorSpell(8000042, "Eat Candy", "Consumable food"),
  PlayerBehaviorSpell(8001419, "Eat Chicken", "Consumable food"),
  PlayerBehaviorSpell(9003084, "Eat Festive Chocolate", "Consumable food"),
  PlayerBehaviorSpell(9003143, "Eat Piero's Chocolate", "Consumable food"),
  PlayerBehaviorSpell(17075, "Eat Red Flower Fruit", "Consumable food"),
  PlayerBehaviorSpell(39220, "Eat Tiny Treasure Taffy", "Consumable food"),
  PlayerBehaviorSpell(22077, "Eat Well-cooked Trout", "Consumable food"),
  // Combat
  PlayerBehaviorSpell(39036, "Defiance", "Player combat ability"),
  // Summons
  PlayerBehaviorSpell(32211, "Summon Mount", "Player mount summon"),
  PlayerBehaviorSpell(41378, "Summon Mount", "Player mount summon"),
  PlayerBehaviorSpell(44779, "Summon Mount", "Player mount summon"),
  PlayerBehaviorSpell(46061, "Summon Mount", "Player mount summon"),
  PlayerBehaviorSpell(46204, "Summon Mount", "Player mount summon"),
  PlayerBehaviorSpell(32213, "Summon Pet", "Player pet summon"),
  PlayerBehaviorSpell(46841, "Summon Pet", "Player pet summon"),
  PlayerBehaviorSpell(33578, "Summon Wyvern", "Player wyvern summon"),
  PlayerBehaviorSpell(46487, "Summon Risopoda", "Player risopoda summon"),
  PlayerBehaviorSpell(37848, "Summon Spooky Anywhere Warehouse", "Player action to summon warehouse access"),
  PlayerBehaviorSpell(8001509, "Summon Spooky Anywhere Warehouse", "Player action to summon warehouse access"),
  // Postal owls
  PlayerBehaviorSpell(27394, "Call Any-Post Owl", "Player postal owl call"),
  PlayerBehaviorSpell(8000400, "Call Any-Post Parrot", "Player postal parrot call"),
  // Crates and chests
  PlayerBehaviorSpell(47416, "Open Akasch Token Crate", "Container opening"),
  PlayerBehaviorSpell(49988, "Open Akasch Token Crate of Honor", "Container opening"),
  PlayerBehaviorSpell(50818, "Open Ancestor's Coinpurse", "Container opening"),
  PlayerBehaviorSpell(36729, "Open Ancestral Crate", "Container opening"),
  PlayerBehaviorSpell(45758, "Open Andelph Machine Design Pouch", "Container opening"),
  PlayerBehaviorSpell(44429, "Open Auroran Synthesis Box", "Container opening"),
  PlayerBehaviorSpell(42428, "Open Blizzard Cloth Armor Crate", "Container opening"),
  PlayerBehaviorSpell(42429, "Open Blizzard Leather Armor Crate", "Container opening"),
  PlayerBehaviorSpell(28073, "Open Bound Eco-Friendly Fuel Bundle", "Container opening"),
  PlayerBehaviorSpell(46239, "Open Bound Serendipity Stone Pouch", "Container opening"),
  PlayerBehaviorSpell(28093, "Open Caernord Shipwright's Design Bag", "Container opening"),
  PlayerBehaviorSpell(48407, "Open Cooperation Reward Crate", "Container opening"),
  PlayerBehaviorSpell(27169, "Open Dean's Coinpurse", "Container opening"),
  PlayerBehaviorSpell(32456, "Open Dean's Research Bundle", "Container opening"),
  PlayerBehaviorSpell(50396, "Open Dimensional Rift Chest", "Container opening"),
  PlayerBehaviorSpell(48482, "Open Disciple's Equipment Chest", "Container opening"),
  PlayerBehaviorSpell(24073, "Open Divine Reward Chest", "Container opening"),
  PlayerBehaviorSpell(23974, "Open Egg", "Container opening"),
  PlayerBehaviorSpell(28095, "Open Enoan Shipwright's Design Bag", "Container opening"),
  PlayerBehaviorSpell(24072, "Open Epic Reward Chest", "Container opening"),
  PlayerBehaviorSpell(28094, "Open Eznan Shipwright's Design Bag", "Container opening"),
  PlayerBehaviorSpell(50819, "Open Garden Coinpurse", "Container opening"),
  PlayerBehaviorSpell(44168, "Open Garden Crate", "Container opening"),
  PlayerBehaviorSpell(44169, "Open Garden Crate", "Container opening"),
  PlayerBehaviorSpell(44170, "Open Garden Crate", "Container opening"),
  PlayerBehaviorSpell(44171, "Open Garden Crate", "Container opening"),
  PlayerBehaviorSpell(44172, "Open Garden Crate", "Container opening"),
  PlayerBehaviorSpell(44173, "Open Garden Crate", "Container opening"),
  PlayerBehaviorSpell(44174, "Open Garden Crate", "Container opening"),
  PlayerBehaviorSpell(44175, "Open Garden Crate", "Container opening"),
  PlayerBehaviorSpell(44176, "Open Garden Crate", "Container opening"),
  PlayerBehaviorSpell(44179, "Open Garden Crate", "Container opening"),
  PlayerBehaviorSpell(45554, "Open Gatekeeper's Reward", "Container opening"),
  PlayerBehaviorSpell(45555, "Open Gatekeeper's Reward", "Container opening"),
  PlayerBehaviorSpell(45556, "Open Gatekeeper's Reward", "Container opening"),
  PlayerBehaviorSpell(45557, "Open Gatekeeper's Reward", "Container opening"),
  PlayerBehaviorSpell(45558, "Open Gatekeeper's Reward", "Container opening"),
  PlayerBehaviorSpell(45560, "Open Gatekeeper's Reward", "Container opening"),
  PlayerBehaviorSpell(31641, "Open Gift Box", "Container opening"),
  PlayerBehaviorSpell(31673, "Open Gift Box", "Container opening"),
  PlayerBehaviorSpell(36710, "Open Glorious Armor Crate", "Container opening"),
  PlayerBehaviorSpell(9003861, "Open Guardian Scramble Winner Chest", "Container opening"),
  PlayerBehaviorSpell(43389, "Open Hereafter Rebellion Reward Crate Rank 2", "Container opening"),
  PlayerBehaviorSpell(43390, "Open Hereafter Rebellion Reward Crate Rank 3", "Container opening"),
  PlayerBehaviorSpell(43393, "Open Hereafter Rebellion Reward Crate Rank 4", "Container opening"),
  PlayerBehaviorSpell(43394, "Open Hereafter Rebellion Reward Crate Rank 5", "Container opening"),
  PlayerBehaviorSpell(43395, "Open Hereafter Rebellion Reward Crate Rank 6", "Container opening"),
  PlayerBehaviorSpell(47433, "Open Hiram Awakening Scrolls", "Container opening"),
  PlayerBehaviorSpell(38863, "Open Hiram Legacy Crate", "Container opening"),
  PlayerBehaviorSpell(41167, "Open Homecoming Warrior Supplies", "Container opening"),
  PlayerBehaviorSpell(41168, "Open Homecoming Warrior Supplies", "Container opening"),
  PlayerBehaviorSpell(41169, "Open Homecoming Warrior Supplies", "Container opening"),
  PlayerBehaviorSpell(41170, "Open Homecoming Warrior Supplies", "Container opening"),
  PlayerBehaviorSpell(41171, "Open Homecoming Warrior Supplies", "Container opening"),
  PlayerBehaviorSpell(41172, "Open Homecoming Warrior Supplies", "Container opening"),
  PlayerBehaviorSpell(41173, "Open Homecoming Warrior Supplies", "Container opening"),
  PlayerBehaviorSpell(41175, "Open Homecoming Warrior Supplies", "Container opening"),
  PlayerBehaviorSpell(41176, "Open Homecoming Warrior Supplies", "Container opening"),
  PlayerBehaviorSpell(41177, "Open Homecoming Warrior Supplies", "Container opening"),
  PlayerBehaviorSpell(41178, "Open Homecoming Warrior Supplies", "Container opening"),
  PlayerBehaviorSpell(41179, "Open Homecoming Warrior Supplies", "Container opening"),
  PlayerBehaviorSpell(41163, "Open Homecoming Warrior Supply Pack", "Container opening"),
  PlayerBehaviorSpell(40943, "Open Improved Desert Pet Accessory Crate", "Container opening"),
  PlayerBehaviorSpell(40944, "Open Improved Lake Pet Accessory Crate", "Container opening"),
  PlayerBehaviorSpell(23140, "Open Jester's Coinpurse", "Container opening"),
  PlayerBehaviorSpell(35285, "Open Jester's Crate", "Container opening"),
  PlayerBehaviorSpell(25535, "Open Librarian's Coinpurse", "Container opening"),
  PlayerBehaviorSpell(32454, "Open Librarian's Research Bundle", "Container opening"),
  PlayerBehaviorSpell(46208, "Open Luna Charm Crate", "Container opening"),
  PlayerBehaviorSpell(47436, "Open Lunar Temper Bundle", "Container opening"),
  PlayerBehaviorSpell(46520, "Open Machine Parts Box", "Container opening"),
  PlayerBehaviorSpell(23138, "Open Merchant's Coinpurse", "Container opening"),
  PlayerBehaviorSpell(35283, "Open Merchant's Crate", "Container opening"),
  PlayerBehaviorSpell(42435, "Open Moonrise Cloth Armor Crate", "Container opening"),
  PlayerBehaviorSpell(47431, "Open Mysterious Hiram Infusion Bundle", "Container opening"),
  PlayerBehaviorSpell(24070, "Open Mythic Reward Chest", "Container opening"),
  PlayerBehaviorSpell(35284, "Open Noble's Crate", "Container opening"),
  PlayerBehaviorSpell(23139, "Open Nobleman's Coinpurse", "Container opening"),
  PlayerBehaviorSpell(45926, "Open Ominous Gold Chest", "Container opening"),
  PlayerBehaviorSpell(27751, "Open Prince's Coinpurse", "Container opening"),
  PlayerBehaviorSpell(35286, "Open Prince's Crate", "Container opening"),
  PlayerBehaviorSpell(33631, "Open Queen's Coinpurse", "Container opening"),
  PlayerBehaviorSpell(35287, "Open Queen's Crate", "Container opening"),
  PlayerBehaviorSpell(47434, "Open Radiant Hiram Awakening Scrolls", "Container opening"),
  PlayerBehaviorSpell(47432, "Open Radiant Hiram Infusions", "Container opening"),
  PlayerBehaviorSpell(49685, "Open Radiant World Boss Chest", "Container opening"),
  PlayerBehaviorSpell(40157, "Open Red Dragon Pouch", "Container opening"),
  PlayerBehaviorSpell(45121, "Open Sanctuary Coinpurse", "Container opening"),
  PlayerBehaviorSpell(42438, "Open Sandroad Cloth Armor Crate", "Container opening"),
  PlayerBehaviorSpell(27168, "Open Scholar's Coinpurse", "Container opening"),
  PlayerBehaviorSpell(32455, "Open Scholar's Research Bundle", "Container opening"),
  PlayerBehaviorSpell(47435, "Open Solar Temper Bundle", "Container opening"),
  PlayerBehaviorSpell(39457, "Open Storage Chest", "Container opening"),
  PlayerBehaviorSpell(42042, "Open Superior Lunarite Pouch", "Container opening"),
  PlayerBehaviorSpell(50820, "Open Zealot's Coinpurse", "Container opening"),
  // Worldgates
  PlayerBehaviorSpell(48564, "Opening Worldgate...", "Worldgate teleportation"),
  PlayerBehaviorSpell(48565, "Opening Worldgate...", "Worldgate teleportation"),
  PlayerBehaviorSpell(48566, "Opening Worldgate...", "Worldgate teleportation"),
  PlayerBehaviorSpell(11216, "Opening Worldgate…", "Worldgate teleportation"),
  PlayerBehaviorSpell(15802, "Opening Worldgate…", "Worldgate teleportation"),
  PlayerBehaviorSpell(49290, "Opening Worldgate…", "Worldgate teleportation"),
  PlayerBehaviorSpell(50350, "Opening Worldgate…", "Worldgate teleportation"),
  PlayerBehaviorSpell(50817, "Opening Worldgate…", "Worldgate teleportation"),
  PlayerBehaviorSpell(50903, "Opening Worldgate…", "Worldgate teleportation"),
  PlayerBehaviorSpell(51310, "Opening Worldgate…", "Worldgate teleportation"),
  PlayerBehaviorSpell(9000823, "Opening Worldgate…", "Worldgate teleportation"),
  // Misc
  PlayerBehaviorSpell(10594, "Recall", "Player recall action"),
  PlayerBehaviorSpell(40911, "Request Ensemble", "Player ensemble request"),
  PlayerBehaviorSpell(33820, "Summon Anywhere Warehouse", "Player action to summon warehouse access"),
).associateBy { it.spellId }

/**
 * Check if a spell ID indicates real player behavior.
 */
fun isPlayerBehaviorSpell(spellId: Int): Boolean = spellId in PLAYER_BEHAVIOR_SPELLS
